### ISSUE TITLE
Cast "test.pike" to program failed

### ISSUE THREAD

**Issue by webhat** [pikelang/Pike#1]
Discovered a bug

Cast "test.pike" to program failed in "/Development/study/pike/broke".
/usr/local/pike/7.8.700/lib/master.pike:1997:

```
int main(int argc, array argv) {
  object r = ((program)"test.pike")();
  r->main(argc,argv);
}
```

`test.pike`
```
int main() {
  write("YAY!");
} 
```

However, when run from hilfe it works fine:
```
> object r = ((program)"test.pike")();                         
> r->main(1,({}));
YAY!(1) Result: 0
```

Pike & Hilfe versions: Pike v7.8 release 700 running Hilfe v3.5 (Incremental Pike Frontend)

**Comment by grubba** [comment]
Well, you are passing argc and argv to the main function in the casted program, but that main doesn't seem to take any arguments.

Skickat i rörligt läge

**Comment by webhat** [comment]
Odd, I don't seem to be able to reproduce this now.

**Comment by arneg** [comment]
Maybe it is possible that you tried from within a different directory before? If the file cannot be found in the current directory, it should give the error you posted.
