### ISSUE TITLE
How can I make a function execute every X seconds?

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#12]
How can I make a function execute every X seconds?
Something equivalent to `setInterval` and `setTimeout` in Javascript!

**Comment by agehall** [comment]
Hi,

http://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/call_out.html is your friend here. Do note that it will run the callback from the backend, so you need to return -1 from your main() to start the backend or it will not work.

/Marcus

**Comment by TheOnlyArtz** [comment]
I see, thanks :) , in order to make it repeat I will have to work with recursions or there's a native solution for that too?
