### ISSUE TITLE
Having issues passing data between classes

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#13]
![image](https://user-images.githubusercontent.com/30025874/49332505-b8ea0e80-f5b6-11e8-97e2-982a8666d6ea.png)

Well this image explains it self. what can I do? here's the full console out put:
![image](https://user-images.githubusercontent.com/30025874/49332510-cf906580-f5b6-11e8-8889-673b64431032.png)

**Comment by agehall** [comment]
Hi,

I’m guessing WSHandler is not an instance variable in the class processing messages so WSHandler->handle resolves to UNDEFINED, but it is hard to be 100% certain without seeing more of the code.

Also, it is better to post text and not screen shots of your problems. That way people can read your questions on any terminal and it is also possible to copy&paste code to test.

/Marcus

**Comment by TheOnlyArtz** [comment]
Thank you Marcus. you've helped me a lot :)
