### ISSUE TITLE
Calendar.pmod/Language.pmod class cCATALAN misspelling from decembre to desembre

### ISSUE THREAD

**Issue by davidtapia** [pikelang/Pike#16]
protected private constant month_names=
   ({
      "gener",
      "febrer",
      "març",
      "abril",
      "maig",
      "juny",
      "juliol",
      "agost",
      "setembre",
      "octubre",
      "novembre",
      "**desembre**",
   });

**Comment by PeterBortas** [comment]
Fixed in 8.1 and 8.0, thanks for the report!

The next stable release containing this fix will probably go out around the new year.
