### ISSUE TITLE
Error when trying to inflate zlib-compressed data using gz

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#17]
So, I'm writing a Discord API Wrapper as can be seen [here](https://github.com/theonlyartz/fisher)
And in order to have faster performance Discord provides to compress the data in a zlib format.
So when I'm getting data from the websocket the frame data looks like that:
![image](https://user-images.githubusercontent.com/30025874/49664803-9abf5b00-fa5b-11e8-8772-050ddf289589.png)
And when I'm trying to inflate with the string I'm getting the next backtrace:
```
Cannot input wide string to gz_inflate->inflate()

C:/Program Files (x86)/Pike/lib/modules/___Gz.so:1: ___Gz.inflate()->inflate(Buffer(4910 /* 9820 */))
C:/Users/win10/Desktop/Fisher/Gateway/WSManager.pike:121: /main()->WSManager()->handleCompression(Protocols.WebSocket.Frame(FRAME_BINARY, fin: 1, 4910 bytes))
C:/Users/win10/Desktop/Fisher/Gateway/WSManager.pike:109: /main()->WSManager()->onmessage(@0=Protocols.WebSocket.Frame(FRAME_BINARY, fin: 1, 4910 bytes))
C:/Program Files (x86)/Pike/lib/modules/Protocols.pmod/WebSocket.pmod:568: Protocols.WebSocket.Connection()->websocket_in(SSL.File(Stdio.File("socket", "gateway.discord.gg:443", 777 /* fd=3 */), SSL.Client
Connection(ready)),"╟W Pw9╜m╟\17≡fFW_\26\35╕T╓ΘC\5\f╜ßG\203\rα0▌\24Φ\t▀]\24\0▌╜n7┐e\214#±\32⌠├j╞\34I»ñw\232ε╪u╖▓╧{\202w\27Θ"+[727]+"\32NC}$╥\237¡ µ°╦\e▀╝∙?v\u00931+")
C:/Program Files (x86)/Pike/lib/modules/SSL.pmod/File.pike:1237: SSL.File(Stdio.File("socket", "gateway.discord.gg:443", 777 /* fd=3 */), SSL.ClientConnection(ready))->internal_poll()
-:1: Pike.Backend(0)->`()(3600.0)
```
```pike
  bool|string handleCompression(Protocols.WebSocket.Frame frame) {
    String.Buffer b = String.Buffer();
    b->add(frame.data);

    write(Gz.inflate()->inflate(b));
    string result = b->get(); // Clear the buffer
  }
```
What is being done wrong?

**Comment by poppa** [comment]
Have you tried passing `frame->data` (use the arrow syntax rather than the dot syntax) directly to `Gz.inflate()->inflate()`. I don't think there's any need to go via `String.Buffer()` here. 

If that fails with the same error, try `Gz.inflate()->inflate(string_to_utf8(frame->data))`. According to the docs `inflate()` expects an `8bit` string, and it might be so that the websocket frame carries a Pike string.

**Comment by TheOnlyArtz** [comment]
> Gz.inflate()->inflate(string_to_utf8(frame->data))

Nice, I tried it and now I'm getting another bug which indicates on an incorrect header check
`Error in gz_inflate->inflate()`

**Comment by TheOnlyArtz** [comment]
UPDATE: this code works:
```pike
  bool|string handleCompression(Protocols.WebSocket.Frame frame) {
    String.Buffer b = String.Buffer();
    b->add(frame->data);

    write(Gz.inflate()->inflate(frame.data));
    string result = b->get(); // Clear the buffer
  }
```
