### ISSUE TITLE
Couple of questions regarding data types

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#18]
Let's say I got a mapping 
```pike
mapping one = ([
  "key1": (["aaa": 1]),
  "key2": (["aaa": 1])
]);
```
- Is there way to get the first key? using an Iterator?
- Is there a way to iterate over the mapping properties?
- Is there a way to access the list keys this mapping has?

- Can I make an Object cast-able to string? (**IMPORTANT**) 

The data types lack descriptive documentation and as one who decided to take the challenge to make a big library with Pike, it's important for me to know all of these stuff related to data types.

**Comment by TheOnlyArtz** [comment]
This is very nice! I actually made a custom sort of data type to fill my needs, and I need help with the 4th question I asked, [here it is](https://github.com/TheOnlyArtz/Fisher/blob/master/Utils/Gallon.pike)
Right now when I will write an instance of the type to the console I will get:
```pike
write("%O", GallonInstanceHere);

> /main()->Gallon()
```
But the result I want is the actual data the object contains, is there a way to do that? 
So I will return the data I want by casting it to string? is it even possible to do make an object cast-able to a string like that?

**Comment by PeterBortas** [comment]
> Can I make an Object cast-able to string? (IMPORTANT)

Sure, implement cast() in the class:

mixed cast(string to)
{
  if( to=="string" )
    return "Hello World!";
  return UNDEFINED;
}

https://pike.lysator.liu.se/generated/manual/modref/ex/lfun_3A_3A/cast.html

> Right now when I will write an instance of the type to the console I will get:
> > /main()->Gallon()

To keep in mind: %O is for debug output, and the default output for classes looks like that. It's not stable over versions and not meant for communicating precise state. But you can make the debug representation of your class more expressive by implementing _sprintf(). Some thing like this:

protected string _sprintf(int op)
{
     if(op == 'O') return sprintf("Discuss.Gallon(state=%s)", connectionstate);
}

If you want to serialize the state of your class for storage or message passing you should implement "encode_value()" and "decode_value()". See http://pike-librarian.lysator.liu.se/piff.xml?module=pike.git&file=lib/modules/ADT.pmod/History.pike&from=0168476a8ed533d0e95dfa44e0869d5d7630fde1&to=f3839f06264c20326bfc16d52e433430b890eabd for an example. It's not the easiest example, but it was the latest one implemented and thus easy to find...

**Comment by TheOnlyArtz** [comment]
> If you want to serialize the state of your class for storage or message passing you should implement "encode_value()" and "decode_value()"

I tried to add 
```pike
mapping encode_value() {
  return iterable;
}
```
What will it give me now? How can I write the Gallon instance to console so it will show the `iterable` property?
I want to achieve `write(GallonInstance) // or something similar to that so it will print the actual mapping`

NOTE: I know I can do this by doing `write("%O", GallonInstance.iterable);` but that's not how I want people to use it since it makes the debugging process way more annoying

**Comment by TheOnlyArtz** [comment]
I've implemented it right now: https://github.com/TheOnlyArtz/Fisher/commit/11c1257f75c9eabcb7b0d2bb59d4ead1b2d9be33
