### ISSUE TITLE
How would I parse Date headers to unix timestamps?

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#19]
Hey! it's me again, obviously :), The Calendar API docs are so outdated! so the FAQ there is somewhat useless, That's why I'm asking here.
 
How would I parse [Date Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date) to a unix timestamp (The seconds since 00:00:00 1970)
Example of a date header: `Mon, 10 Dec 2018 11:15:27 GMT`

**Comment by grubba** [comment]
```
$ pike
Pike v8.0 release 702 running Hilfe v3.5 (Incremental Pike Frontend)
> Calendar.ISO.dwim_time("Mon, 10 Dec 2018 11:15:27 GMT");
(1) Result: Second(Mon 10 Dec 2018 11:15:27 GMT)
```

**Comment by grubba** [comment]
```
> _->unix_time();
(2) Result: 1544440527
```

**Comment by TheOnlyArtz** [comment]
Yep that will do! Cheers
