### ISSUE TITLE
Using `copy_value` won't work as expected.

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#21]
Hey, I'm trying to use [copy_value](https://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/copy_value.html) method.
```pike
  void guildMemberUpdate(mapping data) {
    Guild guild = client.guilds->get(data.guild_id);
    if (!guild) return;

    GuildMember cached = guild.members->get(data.user.id);
    if (!cached) return;

    GuildMember newMember = copy_value(cached);

    newMember.nickname = data.nick; // This line updates the cached one!
    // I don't see how copy_value should work other than cloning values so you can manipulate them
    // in a way that it won't affect the original value.

    write("%O -> %O", cached.nickname, newMember.nickname);
    // "new" -> "new"
  }
```

**Comment by agehall** [comment]
No, I’d say it works exactly as expected.

It clones your object but it does not handle any internals of your object, so all the data within the clone will be the same. I think copy_value() was mostly designed to handle deep copying of arrays, multisets and mappings, not cloning generic objects.

If you want to create clones of your own objects, you are better off implementing a constructor that can take another object as a parameter and then copy data yourself.

However, I would say that the code you show below is flawed - if you actually clone an object and update data in it, what happens to other pieces of code that has references to the older object? Are you sure you don’t want the updates to be reflected there as well?

**Comment by TheOnlyArtz** [comment]
I'm sure I don't want the updates to be reflected there as well since I want to return the new object data next to the cached one
