### ISSUE TITLE
[Question] sandboxing/embedding and syntax addons

### ISSUE THREAD

**Issue by Garagoth** [pikelang/Pike#23]
Hi.

I was wondering: Pike originates from LPC.
I have a very old LPC game driver and I was wondering how much would it take to rewrite it in Pike.

Features I would need:
1. Way of sanboxing/limiting programs running inside game driver, so game programmers have access only to specific part of filesystem (chroot) and only few selected functions are available.
Maybe if it is possible to strip Pike distribution from every module, leaving basically a parser and interpreter (with all language keywords ofc), embedding it into my own C/whatever application and providing all the efuns myself? I would write efuns in C, do all security checks etc there, and provide them to Pike, Pike parses and executes pike code using efuns provided by my implementation. So all Pike I/O would be done via efuns provided by my code.

2. We have a feature that is near lambdas, but more compact - and less flexible, but used all over the mudlib codebase:
    ```c
    int do_something(int a, int b, int c) { return a + b + c; }
    
    int main() {
    function f = &do_something(10, , 2); //lock arguments 1 and 3. Any argument can be locked.
    write(f(1)); //this will call do_something(10, 1, 2)
    }
    ```
    Ampersand here is used to create basically a lambda...
    How difficult would it be to implement this in Pike parser/compiler?
    Is it possible to add operator so:
    `function f = &do_something_else(10, , "a string");`
    is equal to (already existing in Pike):
    `function f = lambda(mixed arg1, mixed arg2) { return do_something_else(10, arg1, "a string", arg2); };`

3. Default function parameters:
    `int do_something(int a, int b = 1, string c = "default") { ... }`
    calling just `do_something(10);` would in fact call `do_something(10, 1, "default");`

    How difficult this would be to implement? I suppose I could work around this by function variants and add defaults this was, but for functions with lots of optional/defaulted arguments this becomes very messy.

4. Function composition operator @. Given g and f are functions and z = g @ f, then z(x) = f(g(x));
    Basically a syntactic sugar around lambdas:
    `function z = g @ f;`
    is equal to (not sure abour varargs syntax here):
    `function z = lambda(mixed... argv) { return f(g(@argv)); };`

5. &->func() syntax, maybe close to point 2:
    The form &->func(args) denotes a function that first expects an object, and when given this object it will call func in it.
    Example:
    ```c
    function f;
    f = &->query_wiz_level();

    /* prints the level of the player */
    write(f(this_player()));
    /* write the names of all wizards that are logged on */
    write(implode(filter(users(), &->query_wiz_level())->query_name(), " "));
    ```

Could you please advise which features are possible to implement fairly easy and where to start looking at the code?
Can it be implemented and maintained externally to pike sources, for example as a C module? From what I already glanced parser is not extensible, so i imagine I would need to maintain my own set of patches and compile, right?

Regards,
Garagoth.

**Comment by tobij** [comment]
Hi,

one thing for you to look at would be to use the Pike compiler with a compilation handler, which is handling which symbols etc are available to the compilation - see http://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/CompilationHandler.html. Using this, you could run a compilation with only "sandbox-ready" functions etc. available to the code.

You could in theory also preprocess the code a bit before you put it into the compiler, which would in theory make it possible to support the &-pseudo-lambdas without any chance to Pike internals.

The `@` operator is already in use in Pike for spliceing in calls (`f(@({1, 2, 3 })` being essentially `f(1, 2, 3)`), so you may into collisions there especially if you try to implement it natively.

As for implementing any of this natively, I do not exactly know what to say. I am sure it comes easier to some than others...

**Comment by tobij** [comment]
At some point @eMBee implemented "Nessie", a version if Pike with Python-like syntax: https://www.osnews.com/story/10169/nessie-the-loch-ness-monster-of-programming-languages/. Since he released it on April 1st, 2005, it was widely regarded as an April Fools joke, but this was iirc done with preprocessing and possibly compilation handlers. Maybe @eMBee still has the code around for that...
