### ISSUE TITLE
An issue I've encountered when using the async http API

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#30]
Hey, I've tried asking yesterday by mail but still didn't get an answer, I hope you won't be mad I'm asking here, so, 5 months have passed and I've finally managed to send an async request the way I wanted to, and, get a response, now, my issue with this is that the request is being resolved and its data have to be sent to a separate callback which seems like it's impossible to have a function like: 
```pike
mixed doRequest(<someParams>) {
  mixed mySession = Protocols.HTTP.Session();
  mixed theRequest = HTTPSession->async_post_url(<uri>. <data>, headers_cb, data_cb, fail_cb);
}
void headers_cb(mixed request) {
  write("%O", request->headers()); 
}

void data_cb(mixed data) {
  write("%O", data);
}

void fail_cb(mixed data) {}
```

Let's say someone wants to call `doRequest`, how will the method return the data being resolved and set to one of the callbacks `(data_cb, headers_cb, fail_cb)`?

~Amit aka TheOnlyArtz.
I've encountered this issue while working on [Fisher](https://github.com/TheOnlyArtz/Fisher/)

**Comment by agehall** [comment]
This is something you will have to code yourself. It is not an issue for core pike nor is it a bug of any kind. How you do this is entirely up to your API-design.

Again, please use the appropriate mailing lists to ask questions.
