### ISSUE TITLE
PUT Requests don't work, they just crash

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#31]
I'm trying to establish a PUT HTTP request since there's no PATCH (Why there's no patch too? :) )
```pike
        response = Protocols.HTTP[lower_case(method) + "_url"](uri,"", data, headers);
```
![image](https://user-images.githubusercontent.com/30025874/56456012-bffb9880-636e-11e9-994f-956a247e450b.png)

What may be the cause? I don't think I'm doing anything wrong

**Comment by agehall** [comment]
You are using the `put_url()` method wrong. Please read the API docs for it.

The way you try to use the convenience methods is very bad coding practice since their signatures are all different. If you read the module documentation, it should be obvious that you are better off using `do_method()` instead.

Also, as I have stated before, issues are typically for bugs. Avoid using GitHub issues to ask general questions - use the mailing lists instead.

**Comment by TheOnlyArtz** [comment]
I don't get the mailing lists can I get relevant info? like, how to subscribe and ask questions from them

**Comment by agehall** [comment]
http://pike.lysator.liu.se/forums/

**Comment by TheOnlyArtz** [comment]
> You are using the `put_url()` method wrong. Please read the API docs for it.
> 
> The way you try to use the convenience methods is very bad coding practice since their signatures are all different. If you read the module documentation, it should be obvious that you are better off using `do_method()` instead.
> 
> Also, as I have stated before, issues are typically for bugs. Avoid using GitHub issues to ask general questions - use the mailing lists instead.


Alright, btw, I don't get how I'm using the PUT wrong, I don't have a file so I'm just sending an empty string and I don't have a connection so I don't send anything at all, I read the documentation and filled the parameters correctly. the query variables are something like
```pike
(["topic": "test"])
```
the headers are something like
```pike
(["Authorization": "TOKEN"])
```
So I don't really get what I'm doing wrong.

**Comment by agehall** [comment]
Read the documentation! Normally people complain about poor docs in Pike and they are usually right, but in this case there is nothing wrong with the docs.

Compare

`.Query put_url(string|Standards.URI url, void|string file, void|mapping(string:int|string|array(string)) query_variables, void|mapping(string:string|array(string)) request_headers, void|Protocols.HTTP.Query con)`

to for example

`.Query get_url(string|Standards.URI url, void|mapping(string:int|string|array(string)) query_variables, void|mapping(string:string|array(string)) request_headers, void|Protocols.HTTP.Query con)`.

See? The signatures are vastly different. In the first instance query variables are the third argument and in the second case they are the second argument.

**Comment by TheOnlyArtz** [comment]
Right! and I'm passing the query variables as the 3rd argument!
I'm sorry I didn't show you the whole relevant code but it looks like
```c
      if (lower_case(method) != "PUT")
        response = Protocols.HTTP[lower_case(method) + "_url"](uri, data, headers);
      else
        response = Protocols.HTTP[lower_case(method) + "_url"](uri,"", data, headers);
```

I am passing the query variables as the 3rd argument!

**Comment by TheOnlyArtz** [comment]
Okay update, I've managed to send `put` request successfully, sorry for everything, from now and then I will use the mailing list! 
can I call `PATCH` method when using `do_method`?

**Comment by agehall** [comment]
Yes, `do_method()` is the method you should be using for this type of thing. And it doesn't really care about what verb you use.

**Comment by TheOnlyArtz** [comment]
Alright, that sounds way better! thank you, checking it out right now.
