### ISSUE TITLE
[BUG] The HTTP library is not not happy about adding Content-Length header

### ISSUE THREAD

**Issue by TheOnlyArtz** [pikelang/Pike#33]
Hey, this is what looks like a bug, for once, I'm trying to send an HTTP request but when I try to set the Content-Length header I get an IO error `I/O error: Error 10054`
The headers I'm sending when this error occurs
```c
([ /* 3 elements */
  "Authorization": "Bot TOKENHERE",
  "Content-Length": 74,
  "User-Agent": "DiscordBot (https://github.com/theonlyartz/Fisher, 0.0.1)"
])
``` 
this will cause the error ^
But when sending the next headers:
```c
([ /* 2 elements */
  "Authorization": "Bot TOKENHERE",
  "User-Agent": "DiscordBot (https://github.com/theonlyartz/Fisher, 0.0.1)"
])
```
The request will be sent and everything will work as expected, I'm using the `do_method` function.

**Comment by agehall** [comment]
If you want to report an issue, at least show a piece of code that demonstrates the issue and that can be run.

**Comment by TheOnlyArtz** [comment]
> If you want to report an issue, at least show a piece of code that demonstrates the issue and that can be run.

Sure, I will try to do that as clear as possible:
We will open a new inspection endpoint at https://pipedream.com

Now run the following code:
```pike
int main() {
  // I don't really care about the types at this point
  mixed uri = Standards.URI("TheEndPointYou'veGenerated");
  mapping data = (["data": "somedata"]);
  int lengthAsJSON = sizeof(Standards.JSON.encode(data));
  mapping headers = ([
    "content-length": lengthAsJSON,
  ]);

  Protocols.HTTP.do_method("POST", uri, data, headers);
  return 0;
}
```
Now look at the endpoint you've opened to inspect HTTP traffic on pipedream (after the program has crashed or just didn't work) and observe a failed request which has aborted.

Now, run the same code but comment that line `"content-length": lengthAsJSON,`
It will send a request just as you would expect and you will be able to view it on pipedream.

**Comment by agehall** [comment]
I'm sorry, but you need to read up on how HTTP works.

Content-length describes the data length and you are currently passing no data to the endpoint, only query variables and headers.

Please read http://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/Protocols/HTTP/do_method.html to see how to properly call `do_method()` with the correct parameters. Also note that you do not need to set content-length as that will be done for you by `do_method()`.

**Comment by TheOnlyArtz** [comment]
> I'm sorry, but you need to read up on how HTTP works.
> 
> Content-length describes the data length and you are currently passing no data to the endpoint, only query variables and headers.
> 
> Please read http://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/Protocols/HTTP/do_method.html to see how to properly call `do_method()` with the correct parameters. Also note that you do not need to set content-length as that will be done for you by `do_method()`.

Alright, I think I understand what you are referring to, how can I fill up 
`do_method` parameters when I don't have the `connection` parameter to pass in? how can I pass nothing but pass something to the data? (since the connection parameter accepts void and it comes before the data)

**Comment by agehall** [comment]
`UNDEFINED`?

**Comment by TheOnlyArtz** [comment]
`UNDEFINED` is a query word? ok, nice to know, appreciate your help!

**Comment by TheOnlyArtz** [comment]
@agehall Hey, there's an issue with the HTTP Library in terms of data escaping, didn't want to put an issue for that since you don't really like that but I'm trying to send some files using the library and turns out Pike escapes the data string so if I send something like
```
string requestBody = "this is a test";```
to `do_method` and inspect the packet, the body of the request is `"this is a test"` and not `this is a test` it looks like the HTTP library escapes everything and it looks like as if data is being sent as `sprint("%O", data);` in the library itself, anything you know about it?

**Comment by agehall** [comment]
Please post a minimized, executable, test-case if you think you've found a bug. It is much more likely that your code is causing the problem rather than there being a problem in the HTTP module as that is one of the most widely used modules in Pike.
