### ISSUE TITLE
Compile to Redhat 9

### ISSUE THREAD

**Issue by jtrindade2** [pikelang/Pike#44]
Hello,

How do we compile to redhat 9 using the source?

With regards,
João Trindade

**Comment by grubba** [comment]
This question is similar to #43.

**Comment by grubba** [comment]
Assuming that you mean Red Hat Enterprise Linux 9 (released 2022-05-17), and not Red Hat 9 (2003-03-31). There should not be any problem compiling on either, but AFAIK no one has compiled Pike on Red Hat 9 for quite a while.

**Comment by jtrindade2** [comment]
Yeah I was talking about Red Hat Enterprise Linux 9, but I wanted to create similiar files that appear in the pre-releases in the Download tab, using the source. For example, the files located in [8.0.1870](https://pike.lysator.liu.se/download/pub/pike/alpha/8.0.1870/). One for a generic Linux, and one for each Red Hat (7,8,9).

**Comment by grubba** [comment]
Ok, you want to make an installer package?

Try `make export` or `make export_forced`.

**Comment by grubba** [comment]
Oops, sorry. Try `make bin_export`.

**Comment by jtrindade2** [comment]
I'll try. Thank you in advance.
