### ISSUE TITLE
Apply Method

### ISSUE THREAD

**Issue by abdellahi-brahim** [pikelang/Pike#46]
Pike already have map and filter. It would be nice to add an apply method. It's syntax would be something like this:

```pike
void apply(array data, function|string f, mixed ...args){
  foreach(data, mixed d){
    if(functionp(f))
      f(d, @args);
    else
      d[f](@args);
  }
}
```

**Comment by eMBee** [comment]
you can achieve this with the array[*] syntax.

essentially apply would be defined as: 

````
array apply(array a; function f, mixed ... args){ 
    return f(a[*], @args); 
}
````

`apply(a, doit, 5);` would be equivalent to `doit(a[*], 5);`

**Comment by abdellahi-brahim** [comment]
Oooh, that is rly cool. Dynamic languages ftw ehehe
